Bug fixes
scanoss/quickscan pull request #4
Opened 2021-05-12 19:58 UTC by isasmendiagus

2021-05-12 20:36 UTC, mscasso-scanoss requested changes

2021-05-12 20:36 UTC, mscasso-scanoss commented on build/afterpack.js
> +  // const executableName = context.packager.executableName;
Why is this commented?

2021-05-12 20:36 UTC, mscasso-scanoss commented on package.json
> +  "versiondate": "05.12.21",
This should be called buildDate, and It have to be updated automatically when the package is generated. Think about that for the next version.

2021-05-12 20:36 UTC, mscasso-scanoss commented on package.json
> +    "appId": "com.scanoss.quickscan.lite",
I would rather not change this one.

2021-05-12 20:36 UTC, mscasso-scanoss commented on package.json
> +      "executableName": "scanoss-quickscan-lite",
remove "scanoss-"

2021-05-12 20:36 UTC, mscasso-scanoss commented on renderer.js
> +      // let copyleft_element = $(row).children().eq(2);
Why is this commented? Please clean unnecessary comments.

2021-05-12 20:36 UTC, mscasso-scanoss commented on scanner.js
> +      //stats.size>winnowing.MIN_FILE_SIZE
Again, be careful with comments

2021-05-12 20:36 UTC, mscasso-scanoss commented on scanner.js
> +    //if(fs.lstatSync(filepath).size > winnowing.MIN_FILE_SIZE)
and here?? Why is this condition disabled?

2021-05-12 20:58 UTC, isasmendiagus commented on build/afterpack.js
> +  // const executableName = context.packager.executableName;
This script is executed when compiling is called. The lines commented caused an inconsistent .desktop file after the compilation is done. 

This script was obtained from here and it is not neccesary for Quickscan
https://github.com/beekeeper-studio/beekeeper-studio/blob/master/build/afterPack.js

2021-05-12 21:01 UTC, isasmendiagus commented on renderer.js
> +      // let copyleft_element = $(row).children().eq(2);
It was a feature requested before and is not longer needed

2021-05-12 21:03 UTC, isasmendiagus commented on scanner.js
> +    //if(fs.lstatSync(filepath).size > winnowing.MIN_FILE_SIZE)
It was for a test. It should not be there

2021-05-14 00:15 UTC, mscasso-scanoss approved these changes

2021-05-14 00:41 UTC, mscasso-scanoss approved these changes

2021-05-14 00:42 UTC, merged